= SAÉ 3.01 2023-2024
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

// Useful definitions
:asciidoc: http://www.methods.co.nz/asciidoc[AsciiDoc]
:icongit: icon:git[]
:git: http://git-scm.com/[{icongit}]
:plantuml: https://plantuml.com/fr/[plantUML]
:vscode: https://code.visualstudio.com/[VS Code]

ifndef::env-github[:icons: font]
// Specific to GitHub
ifdef::env-github[]
:correction:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:icongit: Git
endif::[]

:baseURL: https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5

// Tags
image:{baseURL}/actions/workflows/blank.yml/badge.svg[Bidon] 
image:{baseURL}/actions/workflows/build.yml/badge.svg[Build] 
image:{baseURL}/actions/workflows/tests.yml/badge.svg[Tests] 
image:https://img.shields.io/badge/License-MPL%202.0-brightgreen.svg[License: MPL-2.0, link="https://opensource.org/licenses/MPL-2.0"]
//---------------------------------------------------------------

TIP: Pensez à mettre à jour les infos dans ce fichier pour que les badges pointent sur les résultats effectifs de vos intégrations continue ou sur la bonne licence logicielle.

WARNING: Ce dépôt présente le projet à développer dans le cadre de la SAÉ 3.01 du BUT1 Informatique de l'IUT de Blagnac.

Ce fichier `README.adoc` (dont vous lisez sûrement le rendu HTML automatiquement effectué par GitHUb), fait partie du dépôt initial cloné à partir du lien GitHub classroom qui vous a été donné en cours (https://classroom.github.com/a/fePVlfpN).
Vous trouverez le dépôt "template" qui a servi de base ici : https://github.com/IUT-Blagnac/sae3-01-template. En complément du cours Moodle de la SAE 3.01 (cf. <<liensUtiles>>), ce dépôt template vous permet d'accéder à des exemples d'https://github.com/IUT-Blagnac/sae3-01-template/issues[issues], de https://github.com/IUT-Blagnac/sae3-01-template/releases[releases], ou d'autres artefacts à venir.

toc::[]

== Equipe

Projet est réalisé par::

- https://github.com/BernatSR[Bernat Soldevila]
- https://github.com/DamienZoldyck[Damien Laboute]
- https://github.com/EtienneSalauze[Etienne Salauze]
- https://github.com/YashLeBg[Mohamed Said Y. Anli-Yachourti]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

== Réalisations 

TIP: Mettez ici toutes les informations nécessaire à l'utilisation de votre dépôt (comment on installe votre application, où sont les docs, etc.)

== Gestion de projet & Qualité

Chaque sprint (semaine) vous devrez livrer une nouvelle version de votre application (release).
Utilisez pour cela les fonctionnalités de GitHub pour les https://docs.github.com/en/repositories/releasing-projects-on-github[Releases].

De plus ce fichier `README.adoc` devra être à jour des informations suivantes :

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- Lien vers la doc technique https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5/blob/master/Documentation/Technique/Web_DocTechnique.adoc[Doc technique]
- Lien vers la doc utilisateur https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5/blob/master/Documentation/Utilisateur/Web_DocUtil.adoc[Doc utilisateur]
- Liste des (ou lien vers les) User Stories (ToDo/Ongoing/Done) et % restant : https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5/issues?q=is%3Aopen+is%3Aissue+label%3A%22User+Story%22[User Stories]
- Tests unitaires et plans de test
- Indicateurs de qualité du code (dette technique)

== Partie IoT & Java
- Lien vers le code Python : https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5/blob/master/IOT/PYTHON/sae-iot.py[SAE-Python.py]
- Lien vers la documentation du programme Python : https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5/blob/master/IOT/PYTHON/README.adoc[Documentation-Python.adoc]


== Évaluations hebdomadaires

NOTE: Les notes ci-dessous sont mises à jour directement par les enseignants responsables de la compétence 5.

ifdef::env-github[]
image:https://docs.google.com/spreadsheets/d/e/2PACX-1vR653IOTEDovCXjU49qczSZDmK5SBuM43GbpvTrhGCCSAqzpwCdRXU3ey5Y_IRRac1qUnt-iFlPxS5k/pubchart?oid=1826607166&amp;format=image[link=https://docs.google.com/spreadsheets/d/e/2PACX-1vR653IOTEDovCXjU49qczSZDmK5SBuM43GbpvTrhGCCSAqzpwCdRXU3ey5Y_IRRac1qUnt-iFlPxS5k/pubchart?oid=1826607166&amp;format=image]
endif::[]

ifndef::env-github[]
++++
<iframe width="786" height="430" seamless frameborder="0" scrolling="no" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vR653IOTEDovCXjU49qczSZDmK5SBuM43GbpvTrhGCCSAqzpwCdRXU3ey5Y_IRRac1qUnt-iFlPxS5k/pubchart?oid=1826607166&format=image"></iframe> 
++++
endif::[]
