= SAÉ 3.01 2023-2024 - Documentation technique Web - Équipe 5
:toc:
:toc-title: Table des matières
:sectnums: 
:sectnumlevels: 4

== Présentation du projet
=== Equipe

Projet est réalisé par::

- https://github.com/BernatSR[Bernat Soldevila]
- https://github.com/DamienZoldyck[Damien Laboute]
- https://github.com/EtienneSalauze[Etienne Salauze]
- https://github.com/YashLeBg[Anli-Yachourti MOHAMED SAID Y.]

Tuteur/tutrice enseignant(e) de l'équipe:: mailto:jean-michel.bruel@univ-tlse2.fr[JMB]

=== Contexte
Fondée lors de la crise sanitaire de 2020, MalyArt est une entreprise Toulousaine de vente de produits d'art ( peintures, tableaux, dessins et matériel de dessin ) en ligne. 

L'entreprise a donc besoin d'un site web offrant une vitrine de ses produits, ainsi qu'un espace de vente en ligne. Cela affirmera sa présence sur le marché et lui permettra de se développer au niveau national.

== Architecture 

Le site web de MalyArt est hebergé sur un serveur Apache de l'IUT de Blagnac et trouvable à cette adresse : http://193.54.227.208/~saephp05/index.php

La base de données est une base MySQL.

== Schéma d'enchaînement des pages

Le schéma d'enchaînement des pages du site est disponible https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5/blob/master/Site_eCommerce/Documentation/Sch%C3%A9ma%20encha%C3%AEnement%20des%20pages.png[ici]

== Fonctionnalités du site

=== Affichage des produits
// @author Anli-Yachourti MOHAMED SAID Y.

Cette partie du code permet d'afficher les produits selon la catégorie ou sous-catégorie choisie par l'utilisateur.
Les produits peuvent être filtrés par prix croissant ou décroissant.

image::affichage_produits[affichage des produits]

=== Affichage d'un produit
// @author Anli-Yachourti MOHAMED SAID Y.

Cette partie du code permet d'afficher un produit en particulier.
Et en dessous de la description du produit, on peut voir les commentaires et avis des utilisateurs (si il y en a).
Et si nous sommes connectés, nous pouvons ajouter un commentaire (si on a jamais commenté et noté pour ce produit).

image::affichage_produit[affichage d'un produit]

=== Ajout / modification de produits

=== Modification des informations d'un compte 

Cette partie du code récupère les informations du compte connecté.

image::champs[remplir champs]

La suite du code vérifie ensuite que tous les changements que l'on veut effectuer ne rentrent pas en conflit avec les contraintes que l'on a défini (format du mail, numéro de téléphone ou pseudonyme non utilisés...)
Si tout n'est pas valide, un message d'erreur s'affiche, sinon, les requêtes SQL suivantes sont effectuées :

image::sql_compte[Modification des informations d'un compte code]

=== Affichage de l'historique

Cette partie du code permet d'afficher l'historique de commande du client

image::historique[Historique de commande]

=== Panier
//@author Bernat SOLDEVILA
Sur la page de https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5/blob/master/Site_eCommerce/panier.php[panier] accessible seulement si nous sommes connectés, nous avons plusieurs parties de code. +
Nous avons une partie d'affichage des produits avec un formulaire pour modifier la quantité de chaque produit (cela est traité en début de fichier avec une requête SQL)

Nous avons ensuite un formulaire de total à payer avec une autre requête sql, lors de la validation de formulaire (formulaire contenant des champs de type hidden) l'utilisateur est renvoié vers la page de paiement

=== Paiement
//@author Bernat SOLDEVILA

Cette page de https://github.com/IUT-Blagnac/sae-3-01-devapp-Equipe-5/blob/master/Site_eCommerce/commander.php[paiement] comporte également plusieurs parties. +
Nous avons nottament une partie d'affichage des produits comme pour dans le panier avec seule différence que les valeurs ne sont pas modifiables. +

Nous avons ensuite une partie de choix d'adresses, l'utilisateur peut soit laisser l'adresse sélectionnée par défault soit peut en saisir une nouvelle. Pour saisir une nouvelle adresse, nous avons un formulaire qui lorsque validé, apres avoir fait des vérfications va faire appel à la procédure SQL `UpdateCommandeAdresse`. +

Par la suite l'utilisateur est porté vers un double formulaire de paiement, si l'utilisateur sélectionne l'option de paiement avec paypal, le formulaire de paiement par paypal va apparaitre (Cela est fait avec du javascript). Dans le cas contraire si l'option selectionnée est de paiement par carte, le formulaire de paiement par carte apparait. + 

Pour finir si tous les champs sont saisis, l'utilisateur va pouvoir valider sa commande. Si aucun problème de stock ou autre est trouvé lors de l'appel a `traitementCommande.php` une fenêtre d'alerte comme quoi la commande est validée va apparaitre.

=== Connexion 
//@author Bernat SOLDEVILA
==== Formulaire
Pour la page de formulaire nous avons simplement un formulaire avec deux champs (Nom d'utilisateur et mot de passe) et une case pour le cookie.


==== Traitement

Au niveau du traiement des données de connexion, les données sont récupérée avec `$_POST` et sont encapsulées avec `htmlentities()` pour s'éviter des surprises. + 
Afin de comparer le mot de passe saisi et celui dans la base de données, nous chiffrons le mot de passe saisi en SHA256 et nous le comparons avec celui qui est dans la base de données avec le même nom d'utilisateur. + 
Si nous avons un résultat après cette requête cela veut dire qui le nom d'utilisateur et le mot de passe correspondent, nous allons donc mettre les données de l'utilisateur dans la `$_SESSION`. Eventuellement si l'utilisateur l'a sélectionné ajouter un cookie pour se rappeller du nom d'utilisateur. + 
Puis nous redirigeons vers la page d'ou l'utilisateur venait avec une redirection intelligente (redirection avec toutes les informations `$_GET` eventuelles)

=== Inscription 
//@author Bernat SOLDEVILA
==== Formulaire
Nous avons un grand formulaire avec trois sections, premiere section pour les données du client, deuxième pour son adresse et dernière pour son nom d'utilisateur et mot de passe. Ce mot de passe est demandé deux fois avec une script JavaScript pur check si il correspond à nos standards (>8 caractères, 1 numéro, 1 caractère spécial) et que les deux mots de passe correspondent. 

==== Traitement 
Pour le traitement de l'inscription nous avons encore une fois une utilisation de `htmlentities()` et une redirection intelligente. Nous avons également une multitude de check des formats de données (format du mail, format télefone ...) et un check pour s'assurer que les données sensées être uniques (mail, telefone, nom d'utilisateur) ne sont pas déjà présentes dans la base de données. + 
Après cela, si toutes les données semblent être valides nous avons un appel à la procédure SQL `AjouterClient()` qui va s'occuper de l'ajout de l'utilisateur dans la base de données. En cas d'erreur, nous avons une redirection vers le formulaire avec un message d'erreur customisé qui va apparaitre en fonction de l'erreur. 